services:
  - type: web
    name: vohra-fullstack
    env: node
    rootDir: server
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
