create table if not exists public.contact_enquiries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  service text not null,
  message text not null,
  source_page text default 'contact.html',
  created_at timestamptz not null default now()
);

alter table public.contact_enquiries enable row level security;

drop policy if exists "Allow public enquiry inserts" on public.contact_enquiries;

create policy "Allow public enquiry inserts"
on public.contact_enquiries
for insert
to anon
with check (true);
